language: c

compiler: gcc

branches:
  only:
    - master   
script:
    - make
deploy:
  provider: releases
  api_key: "37cb3e17c76debadc8231a5b37d64c2a9fbd97b3"
  file: "libic.so"
  skip_cleanup: true
  on:
    tags: true
	
after_success:
	- ./upload.sh
os:
  - linux
