language: c

compiler: gcc

script:
    - make
deploy:
  provider: releases
  api_key: "21a5dd0d96022e7264dbadea00833d4230c56cd1"
  file: "libic.so"
  skip_cleanup: true
  on:
    tags: true

os:
  - linux
